name: bpm_client
description: A library that makes it easy to interact with the GetSongBPM API to get beats per minute for many songs.
version: 1.0.0
homepage: https://github.com/mikeroosa/bpm_client
author: Mike Roosa <mike.roosa@thirdbasemedia.com>
documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ^0.12.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0
